### ISSUE TITLE
verifyClaims fails if a managed identity's oid belongs in BoundServicePrincipalIDs and the role has 1 or more BoundGroupIDs

### ISSUE THREAD

**Issue by bhavingandhi01** [hashicorp/vault-plugin-auth-azure#36]
Scenario:
- Create a vault role
- Create a user assigned managed identity
- Take managed identity's object_id (oid) and put it in vault role's bound service principals list
- Create an AAD group
- Assign this AAD group's ID to vault role's bound group IDs.
- Assign managed identity to a VM and try to login to the Vault using managed identity's JWT token at azure auth endpoint for the role created above.
- This fails with error: "groups not authorized"

This happens because in path_login.go's verifyClaims function, there is a fall through in the switch statement:

```
       case len(role.BoundServicePrincipalIDs) > 0:
		if !strListContains(role.BoundServicePrincipalIDs, claims.ObjectID) {
			return fmt.Errorf("service principal not authorized: %s", claims.ObjectID)
		}
	}

	if len(role.BoundGroupIDs) > 0 {
```

so if claims.ObjectID value belongs in role.BoundServicePrincipalIDs, it then continues to do BoundGroupIDs check. 
Ideally, if claims.ObjectID value belongs in role.BoundServicePrincipalIDs, then function can just return success (nil) at that point, without further group claims verification.

One potential fix would be to replace:
`if len(role.BoundGroupIDs) > 0 {`

with
`case len(role.BoundGroupIDs) > 0 :`

(and syntactic adjustments)

**Comment by bhavingandhi01** [comment]
![vault-azure-auth-plugin-behaviors](https://user-images.githubusercontent.com/19499961/103315432-6d470080-49da-11eb-8e2e-c75dde1dd299.PNG)

The image here is my attempt of describing what the current behavior is and what this issue is tracking. 

- First and second columns represent role's configuration (bound service principals and bound groups)
- Third and Fourth columns represent oid and groups claims from the incoming JWT.
- Fifth column is for current behavior.
- Sixth column is for the fix this issue is requesting.

Specifically, this issue is requesting to alter the behavior on rows 17/18 in the image.

In summary:
- Currently service principals and groups are checked in AND relationship.
- The issue here is suggesting to evaluate if this should really be (inclusive) OR relationship.
- The way we setup Vault, most of the vault roles will have AAD group binding (bound_groups list). Occasionally we may want to add a service principal to the bound_service_principals list in a role, but not add it to any AAD group. Current implementation of this plugin does not allow for this behavior because of AND relationship.

Couple of notes:
- In the bound_service_principals list, the code here supports * (wildcard char), this seems like an implementation optimization, as I could not find this documented here: https://www.vaultproject.io/api-docs/auth/azure#create-role
- In the suggested fix, * behavior is unchanged to avoid larger breaking changes.
- Still, the proposed change in rows 17/18 may be conceived as a breaking change, as it alters the behavior in two cases highlighted in the image above.

**Comment by vinay-gopalan** [comment]
Hi @bhavingandhi01 , we recently merged a [feature PR](https://github.com/hashicorp/vault-plugin-auth-azure/pull/45) into the Azure Auth plugin that adds globbing (*) support for the `bound_group_ids` field. Now, the relationship between `bound_service_principal_ids` and `bound_group_ids` is as follows:

- If you only want to skip the BoundGroupID check, set `bound_group_ids=*`
- If you only want to skip the BoundServicePrincipalID check, set `bound_service_principal_ids=*`
- If you set a value for both `bound_service_principal_ids` and `bound_group_ids` other than `*`, both checks will take place
- Setting both fields to `*` simultaneously is disallowed

Hope this helps solve your issue, since you can now choose to skip either of the claim checks. If the problem still persists, please let us know by re-opening the issue.
